apiVersion: apps/v1
kind: Deployment
metadata:
  name: strit-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strit-service
  template:
    metadata:
      labels:
        app: strit-service
    spec:
      containers:
      - name: strit-service
        image: struckchure/stritter_strit_service:v0.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2000
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: strit-service-secret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: strit-service-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: strit-service-secret
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: strit-service-config
                key: DB_PORT
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: strit-service-secret
                key: SECRET_KEY
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: strit-service-config
                key: DB_HOST
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: strit-service-config
                key: API_PORT
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: strit-service-config
                key: DEBUG
---
apiVersion: v1
kind: Service
metadata:
  name: strit-service
spec:
  type: NodePort
  selector:
    app: strit-service
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
      nodePort: 30200
